<?php
/**
 * AccountTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\KigoPro;

use PHPUnit\Framework\TestCase;

/**
 * AccountTest Class Doc Comment
 *
 * @category    Class
 * @description Account
 * @package     Piksel\KigoPro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AccountTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Account"
     */
    public function testAccount()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "logo_url"
     */
    public function testPropertyLogoUrl()
    {
    }

    /**
     * Test attribute "support_email"
     */
    public function testPropertySupportEmail()
    {
    }

    /**
     * Test attribute "support_phone"
     */
    public function testPropertySupportPhone()
    {
    }

    /**
     * Test attribute "phone_country_code"
     */
    public function testPropertyPhoneCountryCode()
    {
    }

    /**
     * Test attribute "business_registration"
     */
    public function testPropertyBusinessRegistration()
    {
    }

    /**
     * Test attribute "merchant_name"
     */
    public function testPropertyMerchantName()
    {
    }

    /**
     * Test attribute "currency"
     */
    public function testPropertyCurrency()
    {
    }

    /**
     * Test attribute "company_information"
     */
    public function testPropertyCompanyInformation()
    {
    }

    /**
     * Test attribute "currency_symbol"
     */
    public function testPropertyCurrencySymbol()
    {
    }

    /**
     * Test attribute "primary_locale"
     */
    public function testPropertyPrimaryLocale()
    {
    }

    /**
     * Test attribute "supported_locales"
     */
    public function testPropertySupportedLocales()
    {
    }

    /**
     * Test attribute "accepted_payment_methods"
     */
    public function testPropertyAcceptedPaymentMethods()
    {
    }

    /**
     * Test attribute "legal_business_name"
     */
    public function testPropertyLegalBusinessName()
    {
    }

    /**
     * Test attribute "legal_address"
     */
    public function testPropertyLegalAddress()
    {
    }
}
