<?php
/**
 * CheckInPolicyTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Piksel\Kigo
 * @author   Piksel
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\Kigo\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * CheckInPolicyTest Class Doc Comment
 *
 * @category    Class
 * @description CheckInPolicy
 * @package     Piksel\Kigo
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class CheckInPolicyTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "CheckInPolicy"
     */
    public function testCheckInPolicy()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_in_start_time_minutes_from_midnight"
     */
    public function testPropertyCheckInStartTimeMinutesFromMidnight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_in_end_time_minutes_from_midnight"
     */
    public function testPropertyCheckInEndTimeMinutesFromMidnight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_out_start_time_minutes_from_midnight"
     */
    public function testPropertyCheckOutStartTimeMinutesFromMidnight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_out_end_time_minutes_from_midnight"
     */
    public function testPropertyCheckOutEndTimeMinutesFromMidnight()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_in_method"
     */
    public function testPropertyCheckInMethod()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_in_off_site"
     */
    public function testPropertyCheckInOffSite()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_in_location"
     */
    public function testPropertyCheckInLocation()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "check_in_instructions"
     */
    public function testPropertyCheckInInstructions()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
