<?php
/**
 * ListingFeeRuleTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\KigoPro;

use PHPUnit\Framework\TestCase;

/**
 * ListingFeeRuleTest Class Doc Comment
 *
 * @category    Class
 * @description ListingFeeRule
 * @package     Piksel\KigoPro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListingFeeRuleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ListingFeeRule"
     */
    public function testListingFeeRule()
    {
    }

    /**
     * Test attribute "guid"
     */
    public function testPropertyGuid()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "public_name"
     */
    public function testPropertyPublicName()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "application"
     */
    public function testPropertyApplication()
    {
    }

    /**
     * Test attribute "qualification"
     */
    public function testPropertyQualification()
    {
    }

    /**
     * Test attribute "calculation_mode"
     */
    public function testPropertyCalculationMode()
    {
    }

    /**
     * Test attribute "rate_value"
     */
    public function testPropertyRateValue()
    {
    }

    /**
     * Test attribute "is_mandatory"
     */
    public function testPropertyIsMandatory()
    {
    }

    /**
     * Test attribute "guest_range_min"
     */
    public function testPropertyGuestRangeMin()
    {
    }

    /**
     * Test attribute "guest_range_max"
     */
    public function testPropertyGuestRangeMax()
    {
    }

    /**
     * Test attribute "los_min"
     */
    public function testPropertyLosMin()
    {
    }

    /**
     * Test attribute "los_max"
     */
    public function testPropertyLosMax()
    {
    }

    /**
     * Test attribute "payee_id"
     */
    public function testPropertyPayeeId()
    {
    }

    /**
     * Test attribute "max_quantity"
     */
    public function testPropertyMaxQuantity()
    {
    }

    /**
     * Test attribute "is_commissionable"
     */
    public function testPropertyIsCommissionable()
    {
    }

    /**
     * Test attribute "is_taxable"
     */
    public function testPropertyIsTaxable()
    {
    }

    /**
     * Test attribute "type_application"
     */
    public function testPropertyTypeApplication()
    {
    }
}
