<?php
/**
 * ListingDiffImpactTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\KigoPro\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * ListingDiffImpactTest Class Doc Comment
 *
 * @category    Class
 * @description ListingDiffImpact
 * @package     Piksel\KigoPro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class ListingDiffImpactTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "ListingDiffImpact"
     */
    public function testListingDiffImpact()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "channel_connection_id"
     */
    public function testPropertyChannelConnectionId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "listing_id"
     */
    public function testPropertyListingId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "impacts"
     */
    public function testPropertyImpacts()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
