<?php
/**
 * PostThreadRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\KigoPro;

use PHPUnit\Framework\TestCase;

/**
 * PostThreadRequestTest Class Doc Comment
 *
 * @category    Class
 * @description PostThreadRequest
 * @package     Piksel\KigoPro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PostThreadRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PostThreadRequest"
     */
    public function testPostThreadRequest()
    {
    }

    /**
     * Test attribute "thread_external_key"
     */
    public function testPropertyThreadExternalKey()
    {
    }

    /**
     * Test attribute "channel_connection_id"
     */
    public function testPropertyChannelConnectionId()
    {
    }

    /**
     * Test attribute "listing_id"
     */
    public function testPropertyListingId()
    {
    }

    /**
     * Test attribute "check_in"
     */
    public function testPropertyCheckIn()
    {
    }

    /**
     * Test attribute "check_out"
     */
    public function testPropertyCheckOut()
    {
    }

    /**
     * Test attribute "location_booking_id"
     */
    public function testPropertyLocationBookingId()
    {
    }

    /**
     * Test attribute "deadline_for_response"
     */
    public function testPropertyDeadlineForResponse()
    {
    }

    /**
     * Test attribute "guest_external_key"
     */
    public function testPropertyGuestExternalKey()
    {
    }

    /**
     * Test attribute "guest_first_name"
     */
    public function testPropertyGuestFirstName()
    {
    }

    /**
     * Test attribute "guest_last_name"
     */
    public function testPropertyGuestLastName()
    {
    }

    /**
     * Test attribute "guest_email"
     */
    public function testPropertyGuestEmail()
    {
    }

    /**
     * Test attribute "guest_locale"
     */
    public function testPropertyGuestLocale()
    {
    }

    /**
     * Test attribute "guest_location"
     */
    public function testPropertyGuestLocation()
    {
    }

    /**
     * Test attribute "guest_user_id"
     */
    public function testPropertyGuestUserId()
    {
    }

    /**
     * Test attribute "metadata"
     */
    public function testPropertyMetadata()
    {
    }
}
