<?php
/**
 * QuoteRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\KigoPro;

use PHPUnit\Framework\TestCase;

/**
 * QuoteRequestTest Class Doc Comment
 *
 * @category    Class
 * @description QuoteRequest
 * @package     Piksel\KigoPro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class QuoteRequestTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "QuoteRequest"
     */
    public function testQuoteRequest()
    {
    }

    /**
     * Test attribute "listing_id"
     */
    public function testPropertyListingId()
    {
    }

    /**
     * Test attribute "check_in_date"
     */
    public function testPropertyCheckInDate()
    {
    }

    /**
     * Test attribute "check_out_date"
     */
    public function testPropertyCheckOutDate()
    {
    }

    /**
     * Test attribute "coupon_code"
     */
    public function testPropertyCouponCode()
    {
    }

    /**
     * Test attribute "num_adults"
     */
    public function testPropertyNumAdults()
    {
    }

    /**
     * Test attribute "num_children"
     */
    public function testPropertyNumChildren()
    {
    }

    /**
     * Test attribute "compute_default_plan_only"
     */
    public function testPropertyComputeDefaultPlanOnly()
    {
    }

    /**
     * Test attribute "requested_optional_fees"
     */
    public function testPropertyRequestedOptionalFees()
    {
    }

    /**
     * Test attribute "lead_guid"
     */
    public function testPropertyLeadGuid()
    {
    }
}
