<?php
/**
 * RateScheduleTest
 *
 * PHP version 7.2
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Piksel\KigoPro\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * RateScheduleTest Class Doc Comment
 *
 * @category    Class
 * @description RateSchedule
 * @package     Piksel\KigoPro
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class RateScheduleTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "RateSchedule"
     */
    public function testRateSchedule()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "payment_plan_guid"
     */
    public function testPropertyPaymentPlanGuid()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "rate_schedule_nights"
     */
    public function testPropertyRateScheduleNights()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
