<?php
/**
 * MessagingApiTest
 * PHP version 7.2
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.2.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Piksel\KigoPro\Test\Api;

use \Piksel\KigoPro\Configuration;
use \Piksel\KigoPro\ApiException;
use \Piksel\KigoPro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MessagingApiTest Class Doc Comment
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */
class MessagingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for channelsV2MessagingMessagesGet
     *
     * Get Messages.
     *
     */
    public function testChannelsV2MessagingMessagesGet()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelsV2MessagingThreadsPost
     *
     * Create a new Thread.
     *
     */
    public function testChannelsV2MessagingThreadsPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelsV2MessagingThreadsTidMessagesIdPut
     *
     * Update a Message.
     *
     */
    public function testChannelsV2MessagingThreadsTidMessagesIdPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelsV2MessagingThreadsTidMessagesPost
     *
     * Create a new Message.
     *
     */
    public function testChannelsV2MessagingThreadsTidMessagesPost()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test case for channelsV2MessagingThreadsTidPut
     *
     * Update a Thread.
     *
     */
    public function testChannelsV2MessagingThreadsTidPut()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
