<?php
/**
 * PropertyHouseRulesApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */

/**
 * Kigo Pro - Channel Manager API
 *
 * https://www.kigoapis.com/pro/v1/swagger/?urls.primaryName=Channel%20Manager%20API%20v2
 *
 * The version of the OpenAPI document: channels-v2
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Piksel\KigoPro;

use \Piksel\KigoPro\Configuration;
use \Piksel\KigoPro\ApiException;
use \Piksel\KigoPro\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * PropertyHouseRulesApiTest Class Doc Comment
 *
 * @category Class
 * @package  Piksel\KigoPro
 * @author   Patrick Leijser
 * @link     https://piksel.nl
 */
class PropertyHouseRulesApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for proV1ContentPropertiesIdHouserulesGet
     *
     * .
     *
     */
    public function testProV1ContentPropertiesIdHouserulesGet()
    {
    }

    /**
     * Test case for proV1ContentPropertiesIdHouserulesPut
     *
     * .
     *
     */
    public function testProV1ContentPropertiesIdHouserulesPut()
    {
    }
}
